# Generated by Django 6.0.3 on 2026-03-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer', 'is_default'), name='unique_default_address_per_customer'),
        ),
    ]
